import 'package:cloud_firestore/cloud_firestore.dart';
import '../../domain/entities/ride.dart';
import '../../domain/entities/user.dart';
import '../../domain/repositories/ride_repository.dart';
import '../../core/exceptions/app_exception.dart';
import '../../domain/services/commission_service.dart';
import '../datasources/firestore_ride_datasource.dart';
import '../datasources/firestore_location_datasource.dart';
import '../datasources/firestore_user_datasource.dart';
import '../models/ride_dto.dart';
import '../models/user_dto.dart';

/// Ride repository implementation
class RideRepositoryImpl implements RideRepository {
  final FirestoreRideDataSource _rideDataSource;
  final FirestoreLocationDataSource _locationDataSource;
  final FirestoreUserDataSource _userDataSource;
  final CommissionService _commissionService;
  final FirebaseFirestore _firestore;

  RideRepositoryImpl({
    FirestoreRideDataSource? rideDataSource,
    FirestoreLocationDataSource? locationDataSource,
    FirestoreUserDataSource? userDataSource,
    CommissionService? commissionService,
    FirebaseFirestore? firestore,
  })  : _rideDataSource = rideDataSource ?? FirestoreRideDataSource(),
        _locationDataSource = locationDataSource ?? FirestoreLocationDataSource(),
        _userDataSource = userDataSource ?? FirestoreUserDataSource(),
        _commissionService = commissionService ?? CommissionService(),
        _firestore = firestore ?? FirebaseFirestore.instance;

  @override
  Future<Ride> createRideRequest(RideRequest request) async {
    try {
      // Check if company has sufficient balance
      final hasSufficientBalance = await _commissionService.hasSufficientBalance(
        request.companyUserId,
      );
      
      if (!hasSufficientBalance) {
        final availableBalance = await _commissionService.getAvailableBalance(
          request.companyUserId,
        );
        throw InsufficientBalanceException(
          'Недостаточно средств. Требуется: ${CommissionService.deliveryFee} сум, Доступно: $availableBalance сум'
        );
      }

      final now = DateTime.now();
      final scheduledPickupTime = now.add(Duration(minutes: request.readyInMinutes));
      
      // Create ride DTO
      final rideDto = RideDto(
        id: '', // Will be generated by Firestore
        companyUserId: request.companyUserId,
        driverUserId: null,
        status: 'pending',
        pickupLocation: request.pickupLocation,
        pickupAddress: request.pickupAddress,
        destination: request.destination,
        destinationAddress: request.destinationAddress,
        requestedAt: Timestamp.now(),
        acceptedAt: null,
        arrivedAt: null,
        completedAt: null,
        fare: null,
        distance: null,
        durationSeconds: null,
        rating: null,
        branchId: request.branchId,
        companyName: request.companyName,
        companyPhone: request.companyPhone,
        recipientName: request.recipientName,
        recipientPhone: request.recipientPhone,
        readyInMinutes: request.readyInMinutes,
        scheduledPickupTime: Timestamp.fromDate(scheduledPickupTime),
      );

      // Create ride in Firestore
      final createdRide = await _rideDataSource.createRide(rideDto);
      
      // Reserve balance from company (25,000 сум)
      await _commissionService.reserveBalance(
        companyId: request.companyUserId,
        rideId: createdRide.id,
      );
      
      return createdRide.toEntity();
    } on InsufficientBalanceException {
      rethrow;
    } catch (e) {
      throw GeneralException('Failed to create ride request: ${e.toString()}');
    }
  }

  @override
  Future<void> acceptRide(String rideId, String driverId) async {
    try {
      // Accept ride and assign driver
      await _rideDataSource.acceptRide(rideId, driverId);
      
      // Update driver availability to busy
      await _userDataSource.updateDriverAvailability(
        driverId,
        AvailabilityStatus.busy,
      );
    } catch (e) {
      throw GeneralException('Failed to accept ride: ${e.toString()}');
    }
  }

  @override
  Future<void> updateRideStatus(String rideId, RideStatus status) async {
    try {
      await _rideDataSource.updateRideStatus(rideId, status);
      
      // If ride is completed or cancelled, update driver availability
      if (status == RideStatus.completed || status == RideStatus.cancelled) {
        final ride = await _rideDataSource.getRideById(rideId);
        if (ride != null && ride.driverUserId != null) {
          await _userDataSource.updateDriverAvailability(
            ride.driverUserId!,
            AvailabilityStatus.available,
          );
        }
      }
    } catch (e) {
      throw GeneralException('Failed to update ride status: ${e.toString()}');
    }
  }

  @override
  Future<void> completeRide(String rideId) async {
    try {
      // Get ride details
      final ride = await _rideDataSource.getRideById(rideId);
      if (ride == null) {
        throw GeneralException('Ride not found');
      }

      if (ride.driverUserId == null) {
        throw GeneralException('Cannot complete ride without assigned driver');
      }

      // Update ride status to completed
      await updateRideStatus(rideId, RideStatus.completed);

      // Deduct reserved balance and process commission
      // This will:
      // 1. Deduct 25,000 сум from company's reservedBalance
      // 2. Add 20,000 сум to driver's balance (80%)
      // 3. Record 5,000 сум commission (20%)
      // 4. Create commission record
      // 5. Update transaction histories
      await _commissionService.deductReservedBalance(
        companyId: ride.companyUserId,
        driverId: ride.driverUserId!,
        rideId: rideId,
      );

      // Send completion notification to company
      await _sendCompletionNotificationToCompany(
        ride.companyUserId,
        rideId,
      );
    } catch (e) {
      throw GeneralException('Failed to complete ride: ${e.toString()}');
    }
  }

  @override
  Future<void> cancelRide(String rideId, String reason) async {
    try {
      // Get ride details
      final ride = await _rideDataSource.getRideById(rideId);
      if (ride == null) {
        throw GeneralException('Ride not found');
      }

      // Update ride status to cancelled with reason
      await _rideDataSource.cancelRide(rideId, reason);

      // Refund reserved balance to company
      // This will return 25,000 сум from reservedBalance back to balance
      await _commissionService.refundReservedBalance(
        companyId: ride.companyUserId,
        rideId: rideId,
      );

      // If driver was assigned, update their availability back to available
      if (ride.driverUserId != null) {
        await _userDataSource.updateDriverAvailability(
          ride.driverUserId!,
          AvailabilityStatus.available,
        );
        
        // Send notification to company about cancellation
        await _sendCancellationNotificationToCompany(
          ride.companyUserId,
          rideId,
          reason,
        );
      }
    } catch (e) {
      throw GeneralException('Failed to cancel ride: ${e.toString()}');
    }
  }

  /// Send cancellation notification to company
  Future<void> _sendCancellationNotificationToCompany(
    String companyUserId,
    String rideId,
    String reason,
  ) async {
    try {
      // Store notification in Firestore for Cloud Functions to send
      await _firestore.collection('notifications').add({
        'userId': companyUserId,
        'title': 'Заказ отменен водителем',
        'body': 'Водитель отменил заказ. Причина: $reason',
        'data': {
          'type': 'ride_cancelled_by_driver',
          'rideId': rideId,
          'reason': reason,
        },
        'createdAt': FieldValue.serverTimestamp(),
        'sent': false,
      });
    } catch (e, stackTrace) {
      // Log error but don't throw - notification failure shouldn't block cancellation
      await _logError(e, stackTrace, 'Failed to send cancellation notification');
    }
  }

  /// Send completion notification to company
  Future<void> _sendCompletionNotificationToCompany(
    String companyUserId,
    String rideId,
  ) async {
    try {
      // Store notification in Firestore for Cloud Functions to send
      await _firestore.collection('notifications').add({
        'userId': companyUserId,
        'title': 'Заказ доставлен успешно!',
        'body': 'Ваш заказ был успешно доставлен',
        'data': {
          'type': 'ride_completed',
          'rideId': rideId,
        },
        'createdAt': FieldValue.serverTimestamp(),
        'sent': false,
      });
    } catch (e, stackTrace) {
      // Log error but don't throw - notification failure shouldn't block completion
      await _logError(e, stackTrace, 'Failed to send completion notification');
    }
  }

  /// Log error using ErrorLogger
  Future<void> _logError(Object error, StackTrace stackTrace, String context) async {
    try {
      // Import ErrorLogger at the top if not already imported
      // For now, we'll use a simple approach
      await _firestore.collection('errorLogs').add({
        'error': error.toString(),
        'stackTrace': stackTrace.toString(),
        'context': context,
        'timestamp': FieldValue.serverTimestamp(),
      });
    } catch (_) {
      // Silently fail if logging fails
    }
  }

  @override
  Stream<Ride?> watchActiveRide(String userId) {
    try {
      return _rideDataSource.watchActiveRide(userId).map((rideDto) {
        return rideDto?.toEntity();
      });
    } catch (e) {
      throw GeneralException('Failed to watch active ride: ${e.toString()}');
    }
  }

  @override
  Future<List<Ride>> getRideHistory(String userId) async {
    try {
      // Get all rides for the user (not just completed/cancelled)
      final rideDtos = await _rideDataSource.getRideHistory(
        userId,
        statusFilter: null, // Get all statuses
      );
      return rideDtos.map((dto) => dto.toEntity()).toList();
    } catch (e) {
      throw GeneralException('Failed to get ride history: ${e.toString()}');
    }
  }

  @override
  Future<List<Driver>> findAvailableDrivers(
    GeoPoint location,
    double radiusKm,
  ) async {
    try {
      // Find drivers within radius using geohashing
      final driversData = await _locationDataSource.findDriversWithinRadius(
        location,
        radiusKm,
      );

      // Convert to Driver entities
      final drivers = <Driver>[];
      for (final driverData in driversData) {
        final driverId = driverData['id'] as String;
        final driverDto = DriverDto.fromMap(driverId, driverData);
        drivers.add(driverDto.toEntity());
      }

      return drivers;
    } catch (e) {
      throw GeneralException('Failed to find available drivers: ${e.toString()}');
    }
  }
}
